### ISSUE TITLE
Error attempt to insert nil object from objects

### ISSUE THREAD

**Issue by swaroopa94** [wootwoot1234/react-native-asset-library-to-base64#2]
Hi,
I am using your module for converting my image to base64 format.

But I am getting the following error:
`
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'`

Can anyone tell me how to solve this.

**Comment by wootwoot1234** [comment]
Maybe.  Can you share your code?

**Comment by swaroopa94** [comment]
Hi this is my code 
```
var ReadImageData = require('NativeModules').ReadImageData;
componentWillMount(){
   //alert("fdfkdl"+this.props.rowData.card_back)
 img_front="http://myappdemo.com:5005/"+this.props.rowData.card_front
 img_back="http://myappdemo.com:5005/"+this.props.rowData.card_back
 ReadImageData.readImage(uri, (imageBase64) => {
console.log(imageBase64);
});

}
```

**Comment by wootwoot1234** [comment]
It doesn't look like `uri` Is defined...
